### ISSUE TITLE
Use over WLAN?

### ISSUE THREAD

**Issue by tobiasredel** [SamEureka/balenaPhono#15]
Hi,

i really like your project - when i am deploying your image it always configures the balenaphone access point wireless lan and disconnects from the primary wireless lan i configures through balena. Is the image intended just to stream / connect through ethernet or how could i use the stream through wireless lan?

Thanks in advance

**Comment by SamEureka** [comment]
@tobiasredel I've been having the same problem and can't seem to figure out how to fix it. The issue seems to be from a change in how the balena wifi-connect image works now. Since you can configure the wifi when you create the balena device, I have just been removing wifi-connect entirely. My setup is always connected and doesn't really need the portability of wifi-connect. I would be happy to write up how do do this if you aren't familiar with using the balena-cli to push an project that you have edited. I can also create another branch in this repository if you are deploying with the "deploy with balena" button.

### To do it yourself: 
> [!NOTE]
> Requires you to install the balena-cli and maybe know the basics on how to use `balena login` & `balena push` commands
1. Download this repository to your local environment
2. Open the `docker-compose.yml` file and remove or comment the following lines:

```YAML
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.firmware: 1
```
3. Save the `docker-compose.yml` file and open the terminal.
4. Build and deploy to your device with this command. (Make sure balena-cli is installed and logged into your balena.io account) `balena push <your-fleet-name> --release-tag "no wifi-connect"`
5. If your balenaPhono device is set to track the latest release it will automatically install. If not set your `Target Release` to the one tagged with "no wifi-connect" 

### Deploy with Balena
> [!IMPORTANT]
> I am going to create a branch that has a "Deploy with Balena" button that will deploy without wifi-connect. I'll comment on this issue with instructions when I am done.
