### ISSUE TITLE
Flashing LED 4x on boot

### ISSUE THREAD

**Issue by Fayrewood** [SamEureka/balenaPhono#17]
Hi, 

My old version (1.04) stopped working, so I have tried to deploy to the latest version, but coming into difficulty.

I have used the Deploy Balena button and tried on two different cards and Pi Zero 1 Ws, but I can't get beyond 4x flashing green LEDs.  I note the caution on the Github page and have checked that the system connections has my persistent wifi details, which I've checked, but the device never appears on my LAN, or in the Fleet.

Could you please point me in the right direction to get back online?
Thanks!

**Comment by Fayrewood** [comment]
Hi,

I resolved the issue earlier today.  

What I did was:

1. Remove all of my Balena Fleet and devices - just in case there was a cached mac address from the same device that I was reusing.
2. Create the image using the Deploy Button.
3. Before inserting it into the Pi, I then added country=GB into the config.yaml.  Then I added an ethernet connection file to ensure that Wifi was the default route to the internet.
4. Popped the card in, and it started working

All up and running now!  Thanks for your efforts - it really is a great deployment and makes life so easy.



I needed to add country=GB into my config.yaml, then add a system-connections entry for ethernet and set it to a low route rate, so that WiFi became the default route.

**Comment by SamEureka** [comment]
I'm so glad you figured it out on your own. I just finished bumping the version am about to push a build to balena.io so people get the new version when using the Deploy button.

I confess that I have very low understanding on the wifi config stuff when not in the US. I imagine that it defaults to some US config because `merica!`

I would like to get the wifi-connect stuff working again. I've seen several other projects are having the same issues with it. I am wondering if we can just pass the ssid and psk as device variables so they are persistent and not wiped on reboot.

I am also going to look into the config.yaml stuff. Someone not quite as tech savvy as you are, won't be able to figure that out!

Anyway, glad you are enjoying the project and find it useful!
//Sam
